### ISSUE TITLE
Playerlist doesn't update when player joins

### ISSUE THREAD

**Issue by anthonymendez** [ChristianKern97/fork#2]
View notes for steps to reproduce. The bug is highlighted on line 27.

Behavior: When I set up the server and joined (the same computer running the server and game), playlist doesn't update. OP-list and Ban-list update just fine. The playlist does not.

[2020_1_5_v0_5_notes_AM.txt](https://github.com/ChristianKern97/nihilus/files/4565027/2020_1_5_v0_5_notes_AM.txt)

System Info:
Intel Core i5-7300HQ
16 Gb of DDR3 @ 2400 Mhz
GTX 1050

**Comment by ChristianKern97** [comment]
I can't reproduce the issue.

Playerlist is syncing by using the server query feature. Is it enabled in server.properties?

**Comment by anthonymendez** [comment]
`enable-query=true`?

If so, yes it's enabled. I attempted to reproduce the bug on my Windows Server computer but can't reproduce. I'll try to reproduce it on my laptop again.

**Comment by anthonymendez** [comment]
I was able to reproduce the issue on my laptop. Will try rerunning as an administrator to see if that fixes it.

**Comment by anthonymendez** [comment]
Yup, that fixes the issue. I probably should've assumed this should be run in administrator no?

**Comment by ChristianKern97** [comment]
Ok so the issue is, that the minecraft server can't start the query wthout admin privileges apperently.
Nihilus for now should not need admin privileges.

This needs further investigation, as i still can't reproduce the issue. I will test it on another machine soon.

**Comment by anthonymendez** [comment]
So if I'm understanding this correctly, it figures out who's playing currently by querying the server? What about going by the server's stdout and just adding/removing from the list as players connect and disconnect?

**Comment by ChristianKern97** [comment]
I thought about that alot, there are several problems with handling this stuff from stdout:
1. You can't be sure, that all server versions use the same syntax for join/leave messages
2. What if someone writes "Any_User joined the game" in the ingame chat

If i can't trace this error down i probably have to use stdout.
