### ISSUE TITLE
Importing Paper Server, user didn't have their items and teleports

### ISSUE THREAD

**Issue by anthonymendez** [ChristianKern97/fork#7]
Version 0.5.1.

Imported my personal Paper Server into Nihilus. The server was imported with no issues. All original settings were also imported. Ran the server, user logged in, server thought it was the first time they logged in, the user noticed they didn't have any of their items or home teleports saved.

[consoleLog.txt](https://github.com/ChristianKern97/nihilus/files/4569417/consoleLog.txt)

The error log was empty.

[server.log](https://github.com/ChristianKern97/nihilus/files/4569422/latest.log)

**Comment by ChristianKern97** [comment]
Can you provide the folder structure of the imported server?

**Comment by anthonymendez** [comment]
Before Import

[before_import.tree.txt](https://github.com/ChristianKern97/nihilus/files/4569809/before_import.tree.txt)

![image](https://user-images.githubusercontent.com/19240897/80909297-12e38c00-8cf5-11ea-81b9-fa7d8a2caf14.png)

After Import

[after_import.tree.txt](https://github.com/ChristianKern97/nihilus/files/4569807/after_import.tree.txt)

![image](https://user-images.githubusercontent.com/19240897/80909308-2ee72d80-8cf5-11ea-846d-61ca06799e30.png)

**Comment by ChristianKern97** [comment]
Ok thank you i found the issue. Will be fixed in the next update.

**Comment by ChristianKern97** [comment]
Actually just to be sure it's the right bug: can you give me server.properties before and after?

**Comment by anthonymendez** [comment]
Yeah sure!

**Comment by anthonymendez** [comment]
[before_server_properties.txt](https://github.com/ChristianKern97/nihilus/files/4569894/before_server_properties.txt)
[after_server_properties.txt](https://github.com/ChristianKern97/nihilus/files/4569895/after_server_properties.txt)

**Comment by ChristianKern97** [comment]
Weird that the world-name property changed. Which folder contains the world with the right player data? world_2 or world_3

**Comment by anthonymendez** [comment]
Should be world_2.
